/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary-fixed-variant": "#3a485b",
        "background": "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "on-tertiary-fixed-variant": "#920028",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "surface": "#f7f9fb",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "new-surface-bg": "#f8f9fb",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#45464d",
        "primary-fixed": "#dae2fd",
        "outline": "#76777d",
        "secondary-fixed-dim": "#b9c7df",
        "tertiary": "#000000",
        "tertiary-fixed": "#ffdada",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-container": "#57657a",
        "on-surface": "#191c1e",
        "secondary-container": "#d5e3fc",
        "surface-variant": "#e0e3e5",
        "secondary": "#515f74",
        "tertiary-container": "#40000c",
        "on-background": "#191c1e",
        "primary": "#000000",
        "inverse-surface": "#2d3133",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary-fixed": "#40000c",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c6c6cd",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#f83256",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "secondary-fixed": "#d5e3fc",
        "on-primary-fixed": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}